apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCrJFhBCfOLNYefwxHRVwA00+Rj7B4Dd4qjfS7DJRnEPnX2Q1v115SqFe1nHbeswOZY82DKAfTm4gXSjEvdLHiLTBJsZIBa1pJWeSN+V37UaZ0bcYPFCLFiYpfTPCMgqjoPeronap22AZWwqj/LGiAqKJ4FPYmAON3hVf1Pe2mgHPLrxrfcRd2MMZq7Lk6XU1fsvMEmOFzipyEHrAFeptDWBZKLmLM1sVW51e3RPzZWfiO/DTq7zFkiEjE7UN+AtCaXlmotm3StiyS1nz2l2t2biLXLAfcLXrA+9D1LY9cf6MeS+oybfH9efSdOH4GVARNA3qzzmvsoJ+d7qZSa36pPuE0NacFse+899bNnbi3h1JMrF7sZ0PQq97CNqovT4ojax/q5WkUBqfe62J+sUTqM8LKiBfkc9FXYvfPrr4777mqvJpFQ5peb0v6FY7RywwNrNbTg9MTXCxoMJmNXtjYFeAzzFsbZpEkhyEq54nDo9Z/FUBFDSmz0QX6rMLweiOgb+e5OAyYe85l9C18NILt5H3vdL0WJkU+/lIndURLItlfO5rsTpUkJlp/7HPOkiRo+Zq8ywYJdpAk6sJpVfmEb80TU3WT75Z6IxHQI9U216lL4L1EuSRyySbj+1YN5YlRDjC0t2rcfZZwDD7lKyvEtOmxYV+yCAdGjm4eftrwYeWSFrrjySRqQUzmrYiT9UFwASLmbRc70FKe/D44j0vo6tgozX3ZC221YKyugz+2n3GmAGXbwcvlYnHzS0V2TFL/70vdxCV0ZPqPSULAMmSsolK6xTzfI04+xlfHcCZ+1Ub5L428DJSK6JQLM9b8y8YRLvbZ+ELSXn8KNAHDpWn7Wi73UktHt7YbJ109p8jl7H9WvmUFB5gf8urDvic4sIl95G9BCfA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

