apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBsBNidiKzv5hkpIxXSVIDBL/fTYOqlG992xGGE7UGuiTXnB5FVJ16r2oo+86NoOJU0ynNhUeKugCcb7JNX4Ww+nz+AlF7XTPXOdfrFEWMP89egBk0YoeoAqCZGBOF8agZUalYudF6cgOjlTY/3bEejWHfBECkkVSLvp/SL0MrFpdh4jx9XLTsVMR9YoLCcDluMgrJxGK/KzoAgxtX6NnLx2+CiCa7wyTytaT4X5uthP/jjd5PgThP36YGugZr3TcVnUiQSps4oJ20aZztAXqUZLHiHp35ePwLTMmbitxRKYlz9xDqO0dk+jnPx/zp0r0zyjFCdJc9Fs3bCZnC5/PoZ3ZJ8Fx+Zw5nI7Z11qxIKmK1gT7v7ile4B/7+lYKHuw+18p5E9eSJiDLKhDeJB6W11FVGZu9EH+w6DIcjoxgBEfKg+tgZi9cQTbiiq9fkhcnXMBpxrWFFCIIut+toGui/vXznlZn0TyPkAZajkR5pfTxTBAzVKP3VAeUZm2LbhkVQ8TxNGueUzMlcQzTts95lLg+dLMFwtBJcpcBHKWR34HNnobwuDtobiOkv+Ml2J4jHZxaKWxzXNwMit5C0Or5aB6nK3Zaia80FgK0w9GMUOofdEeCeyQT7LqTTgFxwp0tizI6B3S1MWWvrOD4mDHw9bYQ8U/TZN9cS90RrUgDuw0fWrBvuc+rxEer2wXxsSmKNAYFCAd3pB1aeFRPi4KIqBn7OT/zorsU9rd3JL3h0Oms79YLiLERPV4uMR3yY1qzEprGRi26Hnnz/NFGtSo+ZywpvPbKVtLtzVrEOD9JB/UnmmOxH2TBayWF/YZHcA0HzzN3FlalHOLY29EXiX0jULM2uMk/lc3opzGS16TX5cR7CpXEaWwjXz4WzTh+4hIesGLDPnQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

