apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAzFf8YSlAQsjeXmWkmee4S8Z15Lly3zFlIj1/ECmXpzdSUIeThrj3bxpuv+Z6wYRjaosxrLJPfmRA0mI9OegULxvQvL+eIxwmsoqyZFfesnvcWI/7ALDRAt3Cx9AHyLk/u4VkBzo5Bnuqb91RbzKtva08Rlq97U5OzwlqDjC5MWi+DEduAIbN5fgKJPqS+JWx6ZwNbjCa5peG9IuXWU8sCxWLKhIv0B1Fu6rKdD1IRigGFwmtuukPLI/vtrUvayMzZi/38SoohXdFFfZlG8NYgwaeltzTKjaS6Nnj4f8GFtRgUa2/e6TYsCBSIOHLTcnxqP3cI5VyNIGZAZnOHoed0Yzzh1+V8ua8u7KfLc6ECT1zrHvHWQLCWmOf/5P9cyed6EIJJBpBvF8InGuRhpEh46ql8YJWkX2muQSHcBa/22wdcfhEWGEorhrv1UrJzv/N7C3uuC0XwYeosYK6BOKvzN3XNTjElHfvW4ITVNz0BaB2M0m3bCKHqm97SEmzjlwjPPmtWPfm71qGZrALukEjJ+2ucMWFqwcYQJz7xouiLayc9zM/oV/9/ch9dBW466/QhYZiK6Hi/b1k071NZ/XONyOGRuqWto6k1ros+4dv1g0pwqy79T3bEHa5aUxLGnnLtOOGlwmgaaJAGgDx00tO7HQAwpHoMk9WNH5WXzun+gZvYpdiK3TJsPJu3tNWeMUgYWYuYRUk+davUsx+1j/BWZI+FZkL2zEQkd64+SVoJIGGczQ0jRiq3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

